<a href="https://colab.research.google.com/github/minsong0206/Sensor-rolling-robot/blob/main/DDN_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

print(tf.__version__)

2.19.0


In [3]:
import tensorflow as tf

print(tf.__version__)
a=tf.random.uniform([2,3],0,1)
print(a)
print(type(a))

2.19.0
tf.Tensor(
[[0.7306378  0.7877737  0.24003649]
 [0.29402256 0.3303969  0.6432152 ]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
import tensorflow as tf
import numpy as np

t=tf.random.uniform([2,3],0,1) #tensorflow로 불러올 때
n=np.random.uniform(0,1,[2,3]) #numpy로 불러올때는 0과1 사이 먼저 쓰고 2by3 행렬임을 정의
#tensorflow는 딥러닝 프레임워크라서 자동 미분/연산 추적등을 위해 텐서의 메타데이터를 항상 표시해준다
print("tensorflow로 생성한 텐서:\n",t,"\n") #백슬레시 안되서 \로 씀 이거는 줄바꿈이다
print("numpy로 생성한 ndarray:\n",n,"\n")

res=t+n
print("덧셈결과 : \n",res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.9987154  0.40957272 0.8137028 ]
 [0.928257   0.20909417 0.04718316]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[0.02065035 0.18825042 0.46371639]
 [0.40608991 0.59942752 0.77007136]] 

덧셈결과 : 
 tf.Tensor(
[[1.0193658  0.59782314 1.2774192 ]
 [1.3343469  0.8085217  0.81725454]], shape=(2, 3), dtype=float32)


In [7]:
import tensorflow as tf
import tensorflow.keras.datasets as ds

#MNIST 읽고 텐서 모양 출력한다
(x_train,y_train),(x_test,y_test)=ds.mnist.load_data()
yy_train=tf.one_hot(y_train,10,dtype=tf.int8)
print("MNIST:", x_train.shape,y_train.shape,yy_train.shape)

#CIFAR-10 읽고 텐서 모양 출력
(x_train,y_train),(x_test,y_test)=ds.cifar10.load_data()
yy_train=tf.one_hot(y_train,10,dtype=tf.int8)
print("CIFAR-10:", x_train.shape,y_train.shape,yy_train.shape)

#Boston Housing 읽고 텐서 모양 출력
(x_train,y_train),(x_test,y_test)=ds.boston_housing.load_data()
print("Boston Housing:", x_train.shape,y_train.shape)

#Reuters 읽고 텐서 모양 출력
(x_train,y_train),(x_test,y_test)=ds.reuters.load_data()
print("Reuters:", x_train.shape,y_train.shape)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step
MNIST: (60000, 28, 28) (60000,) (60000, 10)
170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 11s 0us/step
CIFAR-10: (50000, 32, 32, 3) (50000, 1) (50000, 1, 10)
57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
Boston Housing: (404, 13) (404,)
2110848/2110848 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step
Reuters: (8982,) (8982,)
